### PR TITLE
mana_laser

### PR DESCRIPTION
**Pull request by Wouterz90**
#1343

### CODE REVIEW

**Comment by darklordabc** [comment]
image
This doesnt come up for me, not sure why.

**Comment by Wouterz90** [comment]
It works for me??????

**Comment by darklordabc** [comment]
The particle for the laser seems to not be visible many times.

**Comment by darklordabc** [comment]
Also it works with illusions, it shouldnt. Also plz check that break disables it.

**Comment by darklordabc** [comment]
Also it still works where your dead body is, hilariously.

**Comment by Wouterz90** [comment]
Havent tested the laser being visible now, if this doesn't fix it I need to work on the particle or revert it to laser.

**Comment by darklordabc** [comment]
I dont have sound after uploading it. Are we preaching the laser sound properly?

**Comment by Fapboard** [comment]
It's supposed to only have 25% of its original sound volume for less annoyance factor.

- Regards, Whiteboard.

**Pull request closed without merging**
