### PR TITLE
Lust for life, Fixed number error on level 1. Buff a little bit.

### PR DESCRIPTION
**Pull request by 1ran-wang**
Level 1 maximum regen when you are 0% hp = 1.5%
Level 4 maximum regen  when you are 0% hp = 3 %
I think tank build  should not become popular, So 3% is enough.

### CODE REVIEW

**Comment by 1ran-wang** [comment]
Old version has number error on level 1 which should be 0.05.

**Comment by darklordabc** [comment]
This appears to be a significant nerf to the ability? Am i missing something?

**Comment by darklordabc** [comment]
Also, the changelog change should be in this PR, no reason for it to be its own PR, do you know how to edit multiple files on the same branch, if not I can help you.

**Comment by 1ran-wang** [comment]
Old one is 15% per bonus. New one is 2% per bonus.

**Pull request merged**
