### PR TITLE
Fast Start

### PR DESCRIPTION
**Pull request by Yahnich**
it's all working except for the voting percentage updating, i'm not sure why that's not working (in fact it broke banning's voting percentage as well for some reason)

### CODE REVIEW

**Comment by darklordabc** [comment]
Works great besides a few things. Percentages don't work as you mention. And the display is a bit off.

image
Please make the second box surrounding the vote options have the same width as the top box.

**Comment by darklordabc** [comment]
@TideSofDarK could you have a look and see why the percentages are broke here?

**Comment by darklordabc** [comment]
When the percentages should update, the console spits this error:
`[ W PanoramaScript         ]: !! (s2r://panorama/scripts/custom_game/game_setup.vjs_c, line:3929, col:28) - TypeError: Cannot set property 'text' of null`

The line in the game_setup.vjs that corresponds too:
			`$('#voteCountNoFS').text = '(' + (data.faststart[0] || 0) + ')';`

**Comment by Yahnich** [comment]
i'm not sure how to set the width of the vote box to be the same as the banning one, the size of the panels seem to be set to the size of the text, maybe i could enforce width rules on both of them

**Comment by Yahnich** [comment]
everything fixed, only issue currently is the tooltip is not showing; even though in the panorama debugger it does exist

**Comment by Yahnich** [comment]
everything is functional

**Comment by darklordabc** [comment]
Please move the hard-coded "Players start at level 6..." message to the localization file.

**Comment by darklordabc** [comment]
Few issues so far.
The main one is that the topbar is broken ingame, I dont know if its related to this PR. 
image

And the extra info button is weird. It moves, and it makes the timer move as well once moused over. 
image

**Comment by Yahnich** [comment]
are you sure it's staged correctly and not some outdated version? because i dont have these issues
https://i.imgur.com/FNl0E4F.png

https://i.imgur.com/VLD6FSh.jpg

**Comment by darklordabc** [comment]
Yeah it depends on the resolution for the extra info button. It works fine on some resolutions, but on other resolutions its in a weird position and the timer moves.

**Comment by Yahnich** [comment]
i tried fixing it, either i can place the toolbar in a consistent place or the timer doesn't move, i can't seem to get both to work

**Comment by darklordabc** [comment]
@TideSofDarK can you put some space between the end of the text and the question mark icon. So something like this:
image

**Comment by Yahnich** [comment]
tested in 4:3, 16:10 and 16:9 (standard resolutions); working on those
https://i.imgur.com/sMRgrzB.png

**Comment by darklordabc** [comment]
Merged.

**Pull request closed without merging**
