### PR TITLE
Add Brawler custom skill

### PR DESCRIPTION
**Pull request by 01der**
Hope i did this right...

### CODE REVIEW

**Comment by darklordabc** [comment]
Haven't tested yet, but you are going to need to find new icons, they are far too cartoony and dont match the style of the other icons.

**Comment by OtsoTurpeinen** [comment]
You are missing tooltips.
also... bit lazy even by my standards: brawler_strellect_bonus, brawler_agiellect_bonus

**Comment by DankBudd** [comment]
you have repetitive lines in the lua scripts.

on line 16 you do `if caster:PassivesDisabled() then return end` which will end the script right there.
then again on line 27 you do

	if caster:PassivesDisabled() then 
		count = 0
	end

and this will never actually run, because the script ends on line 16 if the casters passives are disabled

**Comment by 01der** [comment]
Thank you all for you feedback! I hope i fixed it now.
@DankBudd: I took that code from marksmanship.lua and had the same thought that you just told me, but i assumed its needed in some special cases. I can remove it if you guys want, but then i guess we should also remove it from the marksmanship skills.

**Comment by DankBudd** [comment]
the repetitive code makes it so the caster would not lose their stat bonuses when broken if they actually had stat bonuses when the break was applied.
the stats would go away after the break wears off tho.

just remove line 16 and it should be fine

**Comment by 01der** [comment]
@DankBudd Done!

**Comment by darklordabc** [comment]
@01der I added you as a collabrator, for future pull requests, its better to make a branch on this repo, make changes to that branch, and then pull request the branch to the main develop branch. Also, its a good idea to join the developer discord chatroom.

**Comment by 01der** [comment]
@darklordabc Thank you! Github still lists me as contributor and doesn't let me create branches.

**Comment by darklordabc** [comment]
Did you accept the request

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/invitations

**Pull request closed without merging**
