### PR TITLE
Increase bloodseeker_thirst's speed limit.

### PR DESCRIPTION
**Pull request by 1ran-wang**
let it be double of normal'speed limit. Cuz it‘s reachable even in normal Dota map.

### CODE REVIEW

**Comment by 1ran-wang** [comment]
Also fixed the issue that thirst will work on illusions.

**Comment by darklordabc** [comment]
I'm not sure about this one

**Comment by 1ran-wang** [comment]
Then just fix the illusion stuff first.

**Comment by darklordabc** [comment]
How about we increase it to 950, so 200 increase? Sorry, i'm super skeptical about high movement speeds, I generally think its very game breaking.

**Pull request merged**
