### PR TITLE
Removed Wraith Tab + Other minor changes

### PR DESCRIPTION
**Pull request by darklordabc**
1. Removed the wraith abilities tab. 
image
2. All wraith abilities moved to custom abilities.
3. Essence Aura moved to main abilities, because from the outside it works the same way as essence aura, even if it is technically a custom ability.
4. Global break moved to custom abilities. 

@Myrl, I think I removed all old references to wraith abilities, but I might of missed a one or two. I deleted them from 6 files, I hope that was all of them.

### CODE REVIEW

**Comment by Myrl** [comment]
Seems good. I'll test it out.

**Comment by Myrl** [comment]
We'd like an opinion in this one. I suggested an "Events" tab, however, the only skills that would populate it are these skills. That is exactly what this PR is trying to avoid.

To compare the two possibilities. 
An "events" tab would only contain these skills, perhaps for a very long time, but it segregates Valve's custom game skills and LoD's custom game skills.
Merging it with the custom tab might be a bit confusing for some players in that they might be confused for LoD custom game skills.

**Comment by Myrl** [comment]
LGTM

**Comment by darklordabc** [comment]
LGTM

**Comment by Yahnich** [comment]
lgtm

**Comment by darklordabc** [comment]
LGTM

**Pull request merged**
