### PR TITLE
Let Titan's Command affect creep-heroes

### PR DESCRIPTION
**Pull request by crojucuhus**
For spirit bear, Warlock golems, etc

### CODE REVIEW

**Comment by darklordabc** [comment]
This won't affect heroes yeah?

**Comment by crojucuhus** [comment]
Yeah pretty sure DOTA_UNIT_TARGET_BASIC means creeps and creep-heroes. For example if we look at imba_tower_self_repair.txt it says "Aura_Types" "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC" and testing in game shows that it works on spirit bear.

**Comment by darklordabc** [comment]
good enough for me

**Comment by crojucuhus** [comment]
Hmm actually I don't think this worked for some reason

**Pull request merged**
