### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Yahnich**
Tiny grow now scales modelsize up with levels
ogre multicast delay keyvalue added to be linked to spellfixes script value
spellfixes some variable and redundancy cleanup
earthshaker more linked to keyvalues in case of future changes

### CODE REVIEW

**Comment by darklordabc** [comment]
Seems to work well.

**Comment by Myrl** [comment]
Isn't Aftershock independent of the skill's damage type? https://github.com/darklordabc/Legends-of-Dota-Redux/pull/16/commits/99420796b6c8ec5ef14b441843d6c0dfa6278f1c

Consider using math.random(), without the arguments instead. https://github.com/darklordabc/Legends-of-Dota-Redux/pull/16/commits/93701c0f25605621d3c34a73062ca8bef41e24b7

**Comment by Yahnich** [comment]
1: the called ability is aftershock; not the ability being used
2: the arguments are necessary to limit it to 100 (otherwise it creates any random integer between 0 and 1 which can cause the floating point errors im trying to avoid; using math.random(100) is between 1 and 100 which is a 1/99 chance instead of 1/100)
3: does it really matter in a confined lua script

**Comment by Myrl** [comment]
Okay. Thanks for the explanations.

LGTM.

**Comment by Yahnich** [comment]
LGTM

**Comment by darklordabc** [comment]
LGTM

**Comment by Myrl** [comment]
LGTM

**Pull request merged**
