### PR TITLE
Marksmanship splitshot

### PR DESCRIPTION
**Pull request by DankBudd**
**To Do:**
- [x] tooltips

- [x] ability icon. marksmanship redux still needs icon

- [x] thorough testing 

- [ ] redux flags, cost, bans

### CODE REVIEW

**Comment by 01der** [comment]
May i suggest this icon:
https://dota2.gamepedia.com/File:Quelling_Shot_(Wraith)_icon.png

**Comment by DankBudd** [comment]
added suggested icon. almost done with this.

**Comment by darklordabc** [comment]
I couldnt test this, when I try to lock options the menu wont progress, not sure whats wrong.

**Comment by darklordabc** [comment]
I can't notice any damage increase as a level up the ability, also, is the damage reduction only meant to affect the split shots or the main shot itself?

**Comment by DankBudd** [comment]
only the splitshot is reduced. but i think im doing like 0.5% damage decrease instead of 50%. accidentally put `reduction * 0.01` because i was thinking it needs to be a percent.
will fix it soon

**Pull request merged**
