### PR TITLE
changed all dummy units to BaseClass npc_dota_base_additive

### PR DESCRIPTION
**Pull request by DankBudd**

### CODE REVIEW

**Comment by darklordabc** [comment]
But why? And have u tested it?

**Comment by DankBudd** [comment]
have not tested it because im away from home still.
the change is so dummy units dont disable backdoor protection

**Comment by darklordabc** [comment]
I'll merge this but I really hope it doesnt break stuff.

**Comment by DankBudd** [comment]
the only reason i can see this breaking things is if there is code using dummys with npc_dota_creature for the purpose of [creature specific functions.](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API#CDOTA_BaseNPC_Creature)

**Pull request merged**
