### PR TITLE
Shadow Shaman and Arcane Symbiosis

### PR DESCRIPTION
**Pull request by OtsoTurpeinen**
Reducing update rate of arcane symbiosis.
(should fix divided we stand issues)
Disabled courier symbiosis... too many possible issues. Bad idea!
New Shadow shaman perk. 5% chance to hex on targeted spells for 3 seconds.
Changed description in addon_english.txt

### CODE REVIEW

**Comment by darklordabc** [comment]
Still waiting on some changes until merging this one.

**Comment by OtsoTurpeinen** [comment]
Updated the shadow shaman perk as intended but could not test because of the bot crashing issue...

**Comment by darklordabc** [comment]
You should be able to test in tools mode with the latest branch. It doesnt crash, but the bots dont use abilities and play dumb.

**Comment by OtsoTurpeinen** [comment]
Tested and working correctly.

**Pull request merged**
