### PR TITLE
Mutators2018

### PR DESCRIPTION
**Pull request by Wouterz90**
No idea if the options can even be selected right now, might also have bugs.

### CODE REVIEW

**Comment by darklordabc** [comment]
- [x] Can the dropped gold on death be the same model as in the official game? Like the sack of gold? Also it only seems to give 4 gold

- [x] Can we use a better explosion graphic that scales with the amount of damage unleashed in the explosion. So small cloud at lvl 1 and a massive explosion at level 100
Something like this https://giphy.com/gifs/suicide-squad-7D1LNjVtzSclq

- [x] Killstreak mutator gains counters from normal creeps, should be from only non-illusion heroes. 

- [x] Torrent doesnt cast on periodic spellcast, nor does sunstrike. Prehaps ground targetins spells dont work

- [x] Friendly spells dont work right for periodic spells, may need to recode how spells are cast, dependent on what type of spells they are. 

- [ ] Some spells are broken, spells that typically dont work with multicast, e.g. paralysing cask, sunstrike and others. 

- [x] Add more skills to global cast spell: lich_chain_frost, furion_sprout, gyrocopter_homing_missile, keeper_of_the_light_mana_leak, lion_voodoo, omniknight_repel, oracle_false_promise (buggy), tusk_walrus_kick, light_blade, invoker_retro_disarm, dark_seer_surge, dark_seer_ion_shell

**Comment by Wouterz90** [comment]
The gold model is bag of gold from redux, I thought I used the same method as I saw other examples of this item.

Suicide or remote detonate might be better yes.

Good find on the killstreak thing, one time I thought something was up but never saw that again

I would advise against adding projectile spells, seeing as spells need to come from somewhere its might take extremely long to reach the target or give an unfair advantage to players more in the middle of the map.

I don't think friendly spells are that good of an idea. I would keep the list small so epic spells like rupture or torrent get used a lot. If the spells fail with multicast and this is has something to do with the spells.

**Comment by darklordabc** [comment]
Getting this script error
https://hastebin.com/mifenomaho.tex
Dont know if its relevent, but I did change the settings to only have one ability in the list of spells to cast.

**Comment by darklordabc** [comment]
- [x] Fast Runes Mutator  

- [ ] Super Runes, not working yet (x2)

- [ ] Explode on Death: Killing Enemies do not knockback enemies

- [x] Vampire: Needs some improvmenets, additional buffs, popup text at night time

- [ ] Drop Gold on Death: Improve item animation so it spins and add cool particle like in the offical verison https://youtu.be/O6DRExtyPGI?t=1m30s

**Pull request merged**
