### PR TITLE
Item abilities - updated to newest organization

### PR DESCRIPTION
**Pull request by Yahnich**
i mightve missed something with the reorganization

### CODE REVIEW

**Comment by Yahnich** [comment]
LGTM

**Comment by darklordabc** [comment]
Few issues.
1. Icons are not working anymore. 
image
2. Force Staff does not knock down trees if cast on somebody else.
3. Shards of Truesight, is not green, its just regular dust color. 
image
4. Truesight Icon is obscured by healthbar. Please raise it a bit higher above the hero. 
image

**Comment by Yahnich** [comment]
icons are working fine for me, are they in your resources/spellicons? otherwise there might be a stage problem: the dust effect is in fact green (the dust prticles in the air) it's just not very noticeable. i cant do much about the truesight thing being obscured by the healthbar, ive tried but the particle won't be moved

**Comment by darklordabc** [comment]
resources/spellicons?
I cant find that folder structure, can you?
Can't this part be more green? Its clearly white here. 
http://i.imgur.com/SReHqD0.png

**Comment by darklordabc** [comment]
My spell icons are like this (in the compiled version):
image

**Comment by Yahnich** [comment]
/resource/flash3/images/spellicons/aether_range_lod.png needs to exist, the scripts have the correct names so the issue is with you not having the spellicons
also if i make that part green it'll look incredibly tacky but i can change it if you really want

**Comment by darklordabc** [comment]
I did a fresh install, I downloaded your patch. I do have the icons there.
image

**Comment by Yahnich** [comment]
why do your spellicons have the outdated names? they're called aether_range_lod in this update

**Comment by darklordabc** [comment]
Thats what they are called on your pull request patch.

**Comment by Yahnich** [comment]
no they're not? https://i.imgur.com/tIqjqiV.png

**Comment by darklordabc** [comment]
I'll redownload and try again.

**Comment by Yahnich** [comment]
the weird thing is theyve never been called the outdated custom_range etc names since i started this pull request so it shouldn't be named that

**Comment by darklordabc** [comment]
I cant get it to work. I deleted all my old files, besides settings.json, and copied your files over, and now I dont have pitlord or item abilities icons. 
What more, I cant even open the spellicons folder, I'm pretty sure there is a stagging problem.
image

**Comment by darklordabc** [comment]
image
"src/resource/flash3" does not exist, which is probably why the stagging is failing.

**Comment by Yahnich** [comment]
rename it to src\game\resource\flash3" for now, i'll submit a pull request to fix it

**Comment by Yahnich** [comment]
addressed all issues

**Comment by darklordabc** [comment]
Shards of Truesight tooltip is still broken. And could you make the true sight icon a bit smaller.

**Comment by Yahnich** [comment]
done

**Comment by darklordabc** [comment]
Test soon

**Comment by darklordabc** [comment]
Getting better. 
image
Buff tooltip missing some info. 

Also you reverted all of the names of the abilities again and some tooltips updates. But I'll wait unitl everything is working before I do another pull request to fix them.

**Comment by Yahnich** [comment]
i dont understand why the tooltip is not working, i'm calling the property properly so i guess ill just remove the values.

**Comment by Yahnich** [comment]
now that the grouping has been fixed, LGTM

**Comment by darklordabc** [comment]
LGTM

**Comment by darklordabc** [comment]
image
It says 15 for the first level, im not sure if thats just visual or if that is the actual bonus.

**Comment by darklordabc** [comment]
The particles work in the workshop tools, but when I tried it online the particles did not. For some reason the Cherub particles work online, prehaps copy that pull request?

**Comment by darklordabc** [comment]
I tested a second time, and they seem to work now, so I'm unsure.

**Comment by darklordabc** [comment]
Seems to be working well.

**Comment by TideSofDarK** [comment]
LGTM

**Comment by Yahnich** [comment]
LGTM

**Comment by darklordabc** [comment]
This has been merged. Closing.

**Pull request closed without merging**
