### PR TITLE
make stat tomes stat bonuses work on your illusions

### PR DESCRIPTION
**Pull request by DankBudd**
**Ready to Merge**
#1342

### CODE REVIEW

**Comment by darklordabc** [comment]
I couldn't test this as it crashed for me. I would use the agi tome, and then cast mirror image to check if the illusions have the bonus stat, but it crashes right after casting mirror image.

**Comment by DankBudd** [comment]
uhh alright. i never had any crashing issues, but ill look into it

**Comment by DankBudd** [comment]
AllowIllusionDuplicate was making it crash, not really sure why that would be. 
it wasnt even calling OnCreated for the illusions before the crash.

i dont have a fix ready yet, i have it working for custom illusion skills
but for volvos illusions i need a way to tie them to their creators and the unit they were created from, so i can manually give them the tome modifiers.

**Comment by DankBudd** [comment]
kind of a janky fix for volvos illusions, but it works.

**Pull request merged**
