### PR TITLE
Make Healing Aura respect cooldown reductions

### PR DESCRIPTION
**Pull request by DankBudd**

### CODE REVIEW

**Comment by darklordabc** [comment]
Have you tested this yet?

**Comment by DankBudd** [comment]
didnt test because i was having issues with compiling, tested now by just copy pasting the ability and it seems that GetTrueCooldown doesnt work, or at least, it ignores octarine core.

**Comment by darklordabc** [comment]
Hmm, I thought passive abilities didn't get cooldowns reduced? I'm worried if we set a precident here, we will have to adjust all other passive cooldowns. Like does geminate get cooldown reduced with octarine? I havent tested but I dont think it does.

**Comment by DankBudd** [comment]
geminate, jinada, all passives get cd reduction in regular dota. 
[Wiki - Octarine Core: ](https://dota2.gamepedia.com/Octarine_Core) Reduces the cooldown of active, passive and item abilities as well as the replenish time of charge-based abilities.

but you've already set a precident of **Not** giving passives cd reduction with most of the custom abilities that have been added.
Edit: theres already an open issue about people wanting custom passives to respect cd reduction #1132

**Comment by darklordabc** [comment]
So I guess we werent merge this?

**Pull request closed without merging**
