### PR TITLE
More flesh heaps

### PR DESCRIPTION
**Pull request by Wouterz90**
Armor, spell lifesteal and normal lifesteal. I think the values are ok (0.4,0.6,0.8,1) for all of them, please think about them. Also give them another icon ;)

### CODE REVIEW

**Comment by darklordabc** [comment]
people have requested spell cast range quite a bit

**Comment by darklordabc** [comment]
Cast Range is missing a script file.

Spell life steal produces this error:
```
[   Developer            ]: 	...\vscripts\abilities\pudge_flesh_heap_spell_lifesteal.lua:192: in function <...\vscripts\abilities\pudge_flesh_heap_spell_lifesteal.lua:179>
[ W VScript              ]: Script Runtime Error: ...\vscripts\abilities\pudge_flesh_heap_spell_lifesteal.lua:192: attempt to index field 'unit' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]: 	...\vscripts\abilities\pudge_flesh_heap_spell_lifesteal.lua:192: in function <...\vscripts\abilities\pudge_flesh_heap_spell_lifesteal.lua:179>
[ W VScript              ]: Message count limit of 10 hit. Subsequent duplicate messages will be squelched.
```

Life steal produces this error
```
[   Developer            ]: 	...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: in function <...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:179>
[ W VScript              ]: Script Runtime Error: ...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: attempt to perform arithmetic on field 'flesh_heap_value_buff_amount' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]: 	...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: in function <...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:179>
[   Developer            ]: ...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: attempt to perform arithmetic on field 'flesh_heap_value_buff_amount' (a nil value)
[   Developer            ]: stack traceback:
[   Developer            ]: 	...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: in function <...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:179>
[ W VScript              ]: Script Runtime Error: ...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: attempt to perform arithmetic on field 'flesh_heap_value_buff_amount' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]: 	...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:189: in function <...cripts\vscripts\abilities\pudge_flesh_heap_lifesteal.lua:179>
```

**Comment by darklordabc** [comment]
Did you also fix the 2 life steals not working?

**Comment by Wouterz90** [comment]
No didn't see those, will do

Now I did

**Pull request merged**
