### PR TITLE
Wouterz90 globalbreak

### PR DESCRIPTION
**Pull request by Wouterz90**

### CODE REVIEW

**Comment by darklordabc** [comment]
"Silence!" does not sound for enemy players.

**Comment by Wouterz90** [comment]
Needs testing!!

**Comment by darklordabc** [comment]
@Wouterz90 this does work. Enemies can hear the silence! but there is only one strange minor problems. The debuff will only apply if both the caster and target have been visible once in the game to the enemy team. Its not really an issue because all players would be revealed by lvl 6 in most games, but some heros that stayed in jungle for entire game, would not have their passives broke. 
Is there a way you can make it so that breaks all enemies passives, even the ones that have not been revealed yet.

**Comment by darklordabc** [comment]
Actually. It does work in all situations, its only the visual part that does not get applied if players have not been revealed once. Not really an issue, just a cosmetic thing.

**Comment by Myrl** [comment]
Please use 4 spaces rather than hard tabs.

**Comment by darklordabc** [comment]
There was a compiling error when I tried to test it. Something about missing brackets, perhaps a simply spelling mistake. 
image

**Comment by Wouterz90** [comment]
Got it

**Comment by Yahnich** [comment]
still using tabs, but otherwise LGTM

**Comment by darklordabc** [comment]
The shockwave animation does not play.

**Comment by darklordabc** [comment]
Please revert your pull request to this previous version. If you don't know how, I can help, or you can just create a new pull request.
https://github.com/Wouterz90/Legends-of-Dota-Redux/tree/a44caf91fd0a772c1384f252a3522bc0756d3e9f

**Comment by darklordabc** [comment]
The "Silence!" is really loud and sounds weird. Sounds like you are playing it like 10 times all at the same time. Its much louder than all other sounds, and its got a weird modulated sound to it.

**Comment by darklordabc** [comment]
Thats a sound recording of me doing 3 normal spells, and then Silence. Turn down your speakers before the 10 second mark. You've been warned. 
https://drive.google.com/file/d/0B7dpugx95_vaZG1mU0d0Rmp6SHc/view

**Comment by Wouterz90** [comment]
I think it needs testing in an actual game, I have tried several ways to create the sound effects for the players, but perhaps allvision or bots having a weird PlayerID cause the messy sound. I just don't know.

**Comment by Yahnich** [comment]
you can't do global sounds by placing a sound on every enemy you need to use scripts for that

**Comment by SwordBacon** [comment]
You should play a sound on each player's client using EmitSoundOnClient("sound_name", playerID). Use a for-loop to find each player. Then you'll have the sound play once for everyone globally. 

I'm not sure if EmitSoundOnClient works properly anymore, but it's worth a shot. Otherwise it will take some panorama with JS.

**Comment by Wouterz90** [comment]
Yeah I think your John Cena example should be the one to look at. Just haven't had time/motivation to do it

**Comment by Wouterz90** [comment]
I'm pretty sure it does what it should do now, It's silly how much time was wasted on such a simple issue.

**Comment by darklordabc** [comment]
Does'nt work, enemies dont get broken, nor does the white animation play on them. Don't worry, I've merged the older version of the ability that worked, no need to continue, feel free to close this pull request.

**Pull request closed without merging**
