### PR TITLE
Update ban list.

### PR DESCRIPTION
**Pull request by 1ran-wang**
Made zuus_thundergods_wrath no longer work with ArcaneEcho

### CODE REVIEW

**Comment by DankBudd** [comment]
seems weird to have thundergods wrath not work with it while other global skills like haunt or furion ult do

should be all of them or none of them imo

**Comment by darklordabc** [comment]
Yeah, I have a bias against new troll combos, and generally I need to hear good arguments before I will agree to them.

Marksmanship + Grow: Yeah its a powerful combination, but I dont know if its more powerful than feast+fury swipes, or fervor + bash, or blink + borrowed time, or any number of combinations of the top tier abilities, so I don't particularly see why we would ban Two powerful abilities, when there are other lots of powerful combos left. To me this is a powerful combo, but not powerful enough to qualify as a troll combo. Centaur + Dispersion is a troll combo because I feel it is such an easy victory and so little can counter it, but I dont agree thats the case with these two abilities.

Zuus + Arcane Echo: Its defintely powerful and I agree that we should probably deal with it somehow, but I don't think this is the best way because of DankBudd's objection.

**Comment by darklordabc** [comment]
What if we made it that Arcano echo has a much larger cooldown when it double casts ultimates? Like a fixed 60 second cooldown when it double casts an ultimate?

**Comment by 1ran-wang** [comment]
Yes it might be a good idea, Or double the mana cost when casting ultimates

**Comment by darklordabc** [comment]
Will deal with spell echo in another thread.

**Pull request closed without merging**
