### PR TITLE
Item abilities

### PR DESCRIPTION
**Pull request by Yahnich**
tested and working with the exception of truesight reveal; couldn't get bots to use abilities

### CODE REVIEW

**Comment by darklordabc** [comment]
I've made a pull request to your patch
**Things I've changed:**
1. Changed the spell icons and names to be more related to the items:
* Force Dash is now a red Force Staff (matching the color it ejects when used).
* "Arcane Lifesteal" is now "Ocatrine Lifesteal", and the icon is a blue Ocatrine core. 
* "Truesight" is now "Shards of True Sight", making reference to the gem of truesight. Lore has been changed too to match. 

2. Made changes to text.
*Updated force dash description to match force staff description.
*Changed description of Shards of True Sight.
*Changed stat information to be more consistent with other Dota 2 stat information. For example, "MS BONUS" to "BONUS MOVESPEED"

**Things you can change (because I couldn't figure out how)**
1. Make Force Dash target all units, like regular force staff (but not spell immune units, unlike force staff).
2. Force Dash should destroy trees in its wake, like regular force staff. 
3. Change dust color to green, to match the idea of ground up Gem of Truesight being thrown into the air. 
4. Make the stats be percentages in the Octarine Lifesteal. 
image
5. Update the top bar information for the abilities. 
Octarine Lifesteal should say:
image
Force Dash should say:
image

Shards of True Sight is fine as it is.

**Comment by Yahnich** [comment]
radius of truesight should not get bigger; thats not what aether lens does; i can do the rest

**Comment by darklordabc** [comment]
Force dash should get bigger. Hook and blink gets bigger. Is it a technical issue?

**Comment by Yahnich** [comment]
addressed all issues

**Comment by Myrl** [comment]
Please use 4 spaces rather than hard tabs.

**Comment by Yahnich** [comment]
ok sure, but why? it's functionally the same except spaces are more annoying to delete and add

**Comment by Myrl** [comment]
Github displays tabs as 8 spaces. A lot of programmers use spaces rather than tabs.

**Comment by Yahnich** [comment]
ok, done

**Pull request closed without merging**
