### PR TITLE
Infernal blade fix

### PR DESCRIPTION
**Pull request by Wouterz90**

### CODE REVIEW

**Comment by Wouterz90** [comment]
This works now

**Comment by darklordabc** [comment]
when I cast rapidfire with infernal blade on autoattack, it makes the sound and apperance of being cast multiple times, but I dont think its actually stacking. Could make it so that it only gives the appearance and sound of activating once.

**Comment by Wouterz90** [comment]
Changed something so that doesn't happen either. Good find!

**Comment by darklordabc** [comment]
It still happens for me. Try it with rapidfire, it plays the fire flicking animation more many times.

**Pull request merged**
