### PR TITLE
New Ability: Arcane Mastery

### PR DESCRIPTION
**Pull request by TheRisen41**
custom_arcane_mastery 
Adds a new ultimate ability that increases the spell damage, mana regen
and movespeed of a hero for an amount of time. Killing an enemy hero
while under this effect reduces the cooldowns of all other abilities.

Target Type: No Target
Cast Point: 0.4sec
Cooldown: 60sec
Manacost: 100, 125, 150

Spell Damage Increase: 20%, 30%, 40%
Bonus Mana Regen: 100%, 200%, 300%
Cooldown Reduction Per Kill: 5sec, 6sec, 7sec
Bonus Movespeed: 40
Duration: 20sec

### CODE REVIEW

**Comment by TheRisen41** [comment]
Will add gifs tomorrow...

**Comment by TheRisen41** [comment]
Particle Preview:
arcane_mastery_2

Sound Preview:
https://dl.dropboxusercontent.com/u/32606308/arcane_mastery_fx.mp3 (_Warning:_ May be loud!)

**Comment by darklordabc** [comment]
Could you please run the ability down this checklist: https://github.com/darklordabc/Legends-of-Dota-Redux/wiki/Checklist-for-New-Abilities

Doing so could avoid a lot of future hassle.

**Comment by TheRisen41** [comment]
Sure i'll do it tomorrow.

**Comment by TheRisen41** [comment]
I've now run through the list and sorted remaining issues out.

**Pull request merged**
