### PR TITLE
buffed Weak abilities.

### PR DESCRIPTION
**Pull request by 1ran-wang**
This ability now gives you 3200 gold and 100 attack speed in total (but it also require 6 ability points).

The previous version is too weak. I buff the gold bonus and atk speed bonus. 

level 1 Huskar's passive gives you 105 attack speed when you are 50% hp. 
level 1 Troll's passive gives you 105 attack speed when 7 stacks

and one wave of creeps worth more than 500 in middle game. So i believe this buff wont be too strong.

### CODE REVIEW

**Comment by 1ran-wang** [comment]
- [ ] Anomaly
- [ ] Anti-magic
- [ ] Benneng
- [ ] Experience bonus
- [ ] Millitary


- [ ] Root

- [ ] Spell reflect



- [ ] Summon Hawk

- [ ] Transmute


Tick the change that you think It's fine,and rovide feedbacks if you don't like it, 
Once we accept the change I'll do the CHANGELOG update.

Thank you @darklordabc @01der

**Comment by 01der** [comment]
I like all of the changes. I don't think Anti-magic needed the buff, definitely needed the nerf though.
I still would never pick Hawk and Experience bonus I think.

**Comment by 1ran-wang** [comment]
yeah so i nerfed radius. the problem is its too strong on Techies but
kindof too  weak on other heroes

I like all of the changes. I don't think Anti-magic needed the buff,
definitely needed the nerf though.
I still would never pick Hawk and Experience bonus.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/pull/1191#issuecomment-322044765>,
or mute the thread

**Comment by darklordabc** [comment]
Doesnt the buff to roots make it just a much better version of overgrowth ultimate>

**Comment by 1ran-wang** [comment]
duration of our version is 2.5sec
the overgrowth is 3/3.75/4.5

and original root always pick with Eyes in the forest.

hm...what about add 10 sec cooldown on it?

Doesnt the buff to roots make it just a much better version of overgrowth
ultimate>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/pull/1191#issuecomment-322053550>,
or mute the thread

**Comment by 1ran-wang** [comment]
Hit & Run I made it has lowest 8 sec cooldown, so that it will be more usefull.
Last will: increased Damage at higher level. Current one is too weak.
Dragon fireball: I know the original fire ball is OP skill, but nerf the damage rate will make it became a harmless skill since no one will standing in it for 10 sec. I make it has lower duration on low level. and also lowered CD but increased damage rate back to the original one.

**Comment by DankBudd** [comment]
i like all these changes 👍 
the exp skill might have been buffed a little too much, but i think we'll just see how it plays out.

**Comment by TechiesTheOne** [comment]
Hit & Run I made it has lowest 8 sec cooldown, so that it will be more usefull.
Last will: increased Damage at higher level. Current one is too weak.
Dragon fireball: I know the original fire ball is OP skill, but nerf the damage rate will make it became a harmless skill since no one will standing in it for 10 sec. I make it has lower duration on low level. and also lowered CD but increased damage rate back to the original one.

**Pull request merged**
