### PR TITLE
Spell totem

### PR DESCRIPTION
**Pull request by darklordabc**

### CODE REVIEW

**Comment by darklordabc** [comment]
@Deathtal 
I got this error when I cast the ability
```
[   Developer            ]: 	...ster\scripts\vscripts\abilities\deathtal\spell_totem.lua:1: in main chunk
[ W VScript              ]: Script Runtime Error: scripts\vscripts\lib\timers.lua:80: attempt to call method 'CreateByClassname' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]: 	scripts\vscripts\lib\timers.lua:80: in function 'start'
[ W VScript              ]: 	scripts\vscripts\lib\timers.lua:217: in main chunk
[ W VScript              ]: 	[C]: in function 'require'
[ W VScript              ]: 	scripts\vscripts\lib\animations.lua:50: in main chunk
[ W VScript              ]: 	[C]: in function 'require'
[ W VScript              ]: 	...ster\scripts\vscripts\abilities\deathtal\spell_totem.lua:1: in main chunk
[ W VScript              ]: Error running script named abilities/deathtal/spell_totem
```

**Comment by Deathtal** [comment]
@darklordabc 
Updated animations.lua and connected files to the versions I used. I think the problem was that I forgot to update modifier_animation_translate.lua

These changes might effect other abilities. Also did you notice anything about the talents?

**Comment by darklordabc** [comment]
Very cool spell, but there is a few issues:

image
1. It casted shackles correctly when I cast it, but when the duration run out, the shackles animation remained. Leaving the battlefield permanently scared with weird animations
image

2. For some reason when I casted cluster-rockets, the totem channels the ability forever until it dies, when you are only meant to be able to channel the ability for like 3 seconds, for some reason the totem does not obey this channel limit resulting in endless rockets (until it does)
image

3. The Damage reduction buff doesnt decrease damage, it INCREASES hero damage output, also I don't like the damage reduction mechanic, its not intuitive and it seems a weird way to balance out the ability. Also is it physical damage, or all types of damage? I'd rather if you removed the damage reduction mechanic all together
image

4. Why does the ability have basically no cooldown? If it has no cooldown, whats the point of given the totem a duration? 

More testing is probably necessary, which I'll do later.

**Comment by Deathtal** [comment]
Glad you liked it.

Point 1. and 2. seems like the same problem and shouldn't be that hard to fix. In the worst case scenario I'll just dissable channeling abilities for Spell Totem.

3. It reduces ALL damage that you and your totems do. The damage reduction mechanic is the best mechanic I could think of at the time. The plan is for it to be more Totem abilities that are all going to share the totem limit aswell as the debuff. There are going to be all kinds of totems, so the debuff needs to be something that can effect all of them (or atleast most of them). I'm willing to change it so that the debuff is something else, or even different for each totem (let's say Spell Totem has a debuff that increases mana cost, while "Right-Click" Totem has a debuff that reduces attack speed).

4. If I would increase the cooldown it would make it harder to reach the limit. An other option is to have charges instead, but then I would need to remake almost the whole ability. A low cooldown also makes it more actively used while playing, instead of saving it for teamfights you can more freely use it while farming. You bring up a good point about the duration and at the start the totems didn't have a duration, it is something I added recently. I do think that I should decrease the health of the totems.

**Comment by darklordabc** [comment]
Play tested for a while, i casted multiple totems, but after about 5 minutes, I tried to cast a 2nd totem again, and it crashed, this was in the console:
```
[   Developer            ]: scripts\vscripts\lib\timers.lua:80: attempt to call method 'CreateByClassname' (a nil value)
[   Developer            ]: stack traceback:
[   Developer            ]: 	scripts\vscripts\lib\timers.lua:80: in function 'start'
[   Developer            ]: 	scripts\vscripts\lib\timers.lua:217: in main chunk
[   Developer            ]: 	[C]: in function 'require'
[   Developer            ]: 	scripts\vscripts\lib\animations.lua:68: in main chunk
[   Developer            ]: 	[C]: in function 'require'
[   Developer            ]: 	...ster\scripts\vscripts\abilities\deathtal\spell_totem.lua:1: in main chunk
[ W VScript              ]: Script Runtime Error: scripts\vscripts\lib\timers.lua:80: attempt to call method 'CreateByClassname' (a nil value)
[ W VScript              ]: stack traceback:
[ W VScript              ]: 	scripts\vscripts\lib\timers.lua:80: in function 'start'
[ W VScript              ]: 	scripts\vscripts\lib\timers.lua:217: in main chunk
[ W VScript              ]: 	[C]: in function 'require'
[ W VScript              ]: 	scripts\vscripts\lib\animations.lua:68: in main chunk
[ W VScript              ]: 	[C]: in function 'require'
[ W VScript              ]: 	...ster\scripts\vscripts\abilities\deathtal\spell_totem.lua:1: in main chunk
[ W VScript              ]: Error running script named abilities/deathtal/spell_totem
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[   VScript              ]: -lvlmax
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[   VScript              ]: -refresh
[   General              ]: S:Gamerules: entering state 'DOTA_GAMERULES_STATE_GAME_IN_PROGRESS'
[   General              ]: C:Gamerules: entering state 'DOTA_GAMERULES_STATE_GAME_IN_PROGRESS'
[   Client               ]: CDOTA_Hud_Main::EventGameRulesStateChanged DOTA_GAMERULES_STATE_GAME_IN_PROGRESS
[   VScript              ]: Starting Fat Timers.
[   Developer            ]: Allocated 65 probes for a path from Vector( 6662.98, -2431.06, 0.f ) to Vector( 6710.62, -2889.74, 0.f )
[   VScript              ]: npc_dota_hero_dragon_knight
[   Entity System        ]: SERVER: npc_dota_creep_neutral(CDOTA_BaseNPC_Creep_Neutral) 'npc_dota_creep_neutral' [846] thinking for 34.81 ms!!!
[   Entity System        ]: SERVER: npc_dota_creep_lane(CDOTA_BaseNPC_Creep_Lane) 'npc_dota_creep_lane' [916] thinking for 11.79 ms!!!
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
[ W General              ]: Null ability name passed into FindAbilityByName!
[ W Client               ]: Filename abilities/deathtal/spell_totem of modifier modifier_totem_damage_loss was not found!
```
image

**Comment by darklordabc** [comment]
Any movement on this @Deathtal ?

**Pull request closed without merging**
