### PR TITLE
Vote percentages #8

### PR DESCRIPTION
**Pull request by TideSofDarK**
Added vote percentage. Works for not premium users. percentage

### CODE REVIEW

**Comment by darklordabc** [comment]
I've tested this and it does work. But I don't know about the code, as I'm not a programmer.

**Comment by Yahnich** [comment]
i recommend remaking the votepercentage into its own seperate function that does what you want it to do; that way it can be reused for future vote options

**Comment by Yahnich** [comment]
tested, nil votes aren't counted and percentages work fine LGTM

**Comment by darklordabc** [comment]
LGTM

**Comment by TideSofDarK** [comment]
LGTM

**Comment by Yahnich** [comment]
LGTM

**Pull request merged**
